name: hive_built_value_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 2.3.0
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build: ^2.3.1
  source_gen: ^1.2.7
  hive_built_value:
    path: ../hive_built_value
  analyzer: ^6.0.0
  source_helper: ^1.3.3
  dartx: ^1.1.0
  built_value: ^8.4.4
  built_collection: ^5.1.1

dev_dependencies:
  #test: ^1.24.2
  build_test: ^2.1.7
  build_runner: ^2.3.3
  pedantic: ^1.11.1
