name: hive_built_value_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 2.3.2
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.17.0 <3.22.3"

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  hive_built_value:
    path: ../hive_built_value
#  hive_built_value: ^2.3.0
  analyzer: ^6.8.0
  source_helper: ^1.3.4
  dartx: ^1.2.0
  built_value: ^8.9.2
  built_collection: ^5.1.1

dev_dependencies:
  test: ^1.25.8
  build_test: ^2.2.2
  build_runner: ^2.4.11
  pedantic: ^1.11.1

dependency_overrides:
  macros: ^0.0.1
