name: Dart CI

on: [push, pull_request]

jobs:
  test-hive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-platform: [vm, chrome]
        dart-channel: ["2.17.0", "3.4.1"]
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-channel }}
      - name: Install dependencies
        run: dart pub get
        working-directory: hive_built_value
      - name: Run tests
        run: pub run test -p ${{ matrix.test-platform }}
        working-directory: hive_built_value

  test-hive-flutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-channel: [dev, beta, stable]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter-channel }}
      - name: Install dependencies
        run: flutter pub get
        working-directory: hive_built_value_flutter
      - name: Run tests
        run: flutter test
        working-directory: hive_built_value_flutter

  test-hive_generator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart-channel: ["2.17.0", "3.4.1"]
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart-channel }}
      - name: Install dependencies
        run: dart pub get
        working-directory: hive_built_value_generator/example
      - name: Generate build_runner output
        run: pub run build_runner build --delete-conflicting-outputs
        working-directory: hive_built_value_generator/example

  check-score:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [hive_built_value, hive_built_value_generator, hive_built_value_flutter]
    steps:
      - uses: actions/checkout@v1
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: ${{ matrix.package }}
          minAnnotationLevel: warning
