name: hive_built_value
description: Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
version: 2.3.2
homepage: https://github.com/hivedb/hive/tree/master/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.17.0 <3.22.3"

dependencies:
  crypto: ^3.0.3
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.8
  mocktail: ^1.0.4
  lints: ^4.0.0
  path: ^1.9.0
  pointycastle: ^3.9.1
  build_runner: ^2.4.11
